name = "Heteregenous_Agent_Model"
uuid = "599d85dc-d1f6-4f2a-bb18-2021950229ab"
authors = ["tfaria <thomas.faria@ensae.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
